try{
  let a;
  console.log(a.length)
  console.log("hi from try")
}
catch(e){
  console.log("hi from catch")
}
console.log("hi i will be printed irresppective of any errroee that might occur")

//if an errroe occurs and we dont use try catch the code stops threre itself 
//but try catch hepls us keep the program running